-- Setup Churn Prediction Notebook on Container Runtime
-- Run this after uploading the notebook file to the stage
-- Prerequisite: Run setup.sql first (creates PYPI_ACCESS EAI)

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

-- 1. Create demo compute pool (if not exists)
CREATE COMPUTE POOL IF NOT EXISTS CHURN_MODEL_POOL
  MIN_NODES = 1
  MAX_NODES = 2
  INSTANCE_FAMILY = CPU_X64_L
  AUTO_SUSPEND_SECS = 300
  AUTO_RESUME = TRUE;

-- 2. Create stage for notebooks (if not exists)
CREATE STAGE IF NOT EXISTS CHURN_PREDICTION_DEMO.ML.NOTEBOOKS;

-- 3. Upload notebook to stage (run from CLI):
-- snow stage copy notebooks/churn_prediction.ipynb @CHURN_PREDICTION_DEMO.ML.NOTEBOOKS --overwrite

-- 4. Create notebook on Container Runtime
CREATE OR REPLACE NOTEBOOK IDENTIFIER('CHURN_PREDICTION_DEMO.ML.CHURN_PREDICTION_NOTEBOOK')
  FROM '@CHURN_PREDICTION_DEMO.ML.NOTEBOOKS'
  MAIN_FILE = 'churn_prediction.ipynb'
  QUERY_WAREHOUSE = 'COMPUTE_WH'
  COMPUTE_POOL = 'CHURN_MODEL_POOL'
  RUNTIME_NAME = 'SYSTEM$BASIC_RUNTIME';

-- 5. Add live version
ALTER NOTEBOOK CHURN_PREDICTION_DEMO.ML.CHURN_PREDICTION_NOTEBOOK ADD LIVE VERSION FROM LAST;

-- 6. Attach EAI for pip install (PYPI_ACCESS created in setup.sql)
ALTER NOTEBOOK CHURN_PREDICTION_DEMO.ML.CHURN_PREDICTION_NOTEBOOK
  SET EXTERNAL_ACCESS_INTEGRATIONS = (PYPI_ACCESS);

-- 7. Transfer ownership to SYSADMIN (notebooks owned by ACCOUNTADMIN cannot run on Container Runtime)
GRANT OWNERSHIP ON COMPUTE POOL CHURN_MODEL_POOL TO ROLE SYSADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON NOTEBOOK CHURN_PREDICTION_DEMO.ML.CHURN_PREDICTION_NOTEBOOK TO ROLE SYSADMIN REVOKE CURRENT GRANTS;

-- Verify setup
SHOW NOTEBOOKS LIKE 'CHURN_PREDICTION_NOTEBOOK' IN SCHEMA CHURN_PREDICTION_DEMO.ML;
DESCRIBE COMPUTE POOL CHURN_MODEL_POOL;
